version: "3.9"

services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "winery"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d winery" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  envoy:
    image: envoyproxy/envoy-dev:b145180d17cac80aa5f9a7801429d52017fea6d1
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8082:8082"
      - "9901:9901"
      - "9993:9993"