server:
  port: 8080

spring:
  jpa:
    hibernate:
      dll-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update


  datasource:
    url: jdbc:postgresql://localhost:5432/winery
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    loadbalancer:
      ribbon:
        enable: false

jwt:
  header:
    Authorization
  secret:
    light
  time:
    #min
    access-expired:
      100
    refresh-expired:
      30000
    accept:
      300
  issuer:
    app