// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ru.spmi.winery.controllers.grpc.greet;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spmi_winery_controllers_grpc_greet_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spmi_winery_controllers_grpc_greet_Greeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spmi_winery_controllers_grpc_greet_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_spmi_winery_controllers_grpc_greet_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\022%ru.spmi.winery.controller" +
      "s.grpc.greet\"1\n\010Greeting\022\022\n\nfirst_name\030\001" +
      " \001(\t\022\021\n\tlast_name\030\002 \001(\t\"Q\n\014GreetRequest\022" +
      "A\n\010greeting\030\001 \001(\0132/.ru.spmi.winery.contr" +
      "ollers.grpc.greet.Greeting\"\037\n\rGreetRespo" +
      "nse\022\016\n\006result\030\001 \001(\t2\204\001\n\014GreetService\022t\n\005" +
      "Greet\0223.ru.spmi.winery.controllers.grpc." +
      "greet.GreetRequest\0324.ru.spmi.winery.cont" +
      "rollers.grpc.greet.GreetResponse\"\000B\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_spmi_winery_controllers_grpc_greet_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_spmi_winery_controllers_grpc_greet_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spmi_winery_controllers_grpc_greet_Greeting_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spmi_winery_controllers_grpc_greet_GreetRequest_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_spmi_winery_controllers_grpc_greet_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_spmi_winery_controllers_grpc_greet_GreetResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
