// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ru.spmi.winery.controllers.grpc.greet;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.spmi.winery.controllers.grpc.greet.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
