// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package ru.spmi.winery.controllers.grpc.greet;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.spmi.winery.controllers.grpc.greet.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.spmi.winery.controllers.grpc.greet.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.ru.spmi.winery.controllers.grpc.greet.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  ru.spmi.winery.controllers.grpc.greet.Greeting getGreeting();
  /**
   * <code>.ru.spmi.winery.controllers.grpc.greet.Greeting greeting = 1;</code>
   */
  ru.spmi.winery.controllers.grpc.greet.GreetingOrBuilder getGreetingOrBuilder();
}
